Feat/cypress automation
lightning-js/blits-example-app pull request #23
Opened 2024-07-11 10:36 UTC by sandeep-vedam

Added Cypress tests

2024-07-18 09:33 UTC, michielvandergeest commented on tests/cypress/e2e/blitsExampleTest.cy.js
> +    cy.visit('http://localhost:5173')
Will this port always be 5173? Shouldn't this be configurable / dynamic?

2024-07-18 14:19 UTC, michielvandergeest requested changes
Looking at the PR I think it mostly looks good, so thanks for this work! 👍 

I ran the tests locally and all 27 failed though. Not sure if that's to do with my setup, but let's double check this.

Also I notice that files are added to the `test\cypress` folder (`reports` and `screenshots`. I don't think these should be added to version control? If so we need to add those paths to the git ignore.

Finally, I think the NPM script commands became a bit confusing, since the backstop related commands are in a different format than the cypress tests. I guess it will be more clear to add a reference to backstop to the backstop tests as well (i.e. test:backstop:reference or something like that)

Other than that, great work!

2024-07-19 09:45 UTC, sandeep-vedam commented
> Looking at the PR I think it mostly looks good, so thanks for this work! 👍
> 
> I ran the tests locally and all 27 failed though. Not sure if that's to do with my setup, but let's double check this.
> 
> Also I notice that files are added to the `test\cypress` folder (`reports` and `screenshots`. I don't think these should be added to version control? If so we need to add those paths to the git ignore.
> 
> Finally, I think the NPM script commands became a bit confusing, since the backstop related commands are in a different format than the cypress tests. I guess it will be more clear to add a reference to backstop to the backstop tests as well (i.e. test:backstop:reference or something like that)
> 
> Other than that, great work!

Hey @michielvandergeest 
Thanks for reviewing the PR. I have updated the PR as per your comments. 

Regarding the backstopJS I have an update in another PR
https://github.com/lightning-js/blits-example-app/pull/24

2024-09-17 11:22 UTC, uguraslan commented
Hey @sandeep-vedam,

I just wanted to share my test results. I ran the tests using both `npm run test:cypress-headed` and `npm run test:cypress`, and in both cases, all tests failed (0/27 passed).

To compare, I also ran the BackstopJS tests, where 15 tests failed (18/23 passed).

I believe the computer's performance, particularly the animation speed, is impacting the test results. When writing the BackstopJS tests, I added many delays to account for performance differences across machines (also configuration options). I tested on two different computers to find delay values that would produce consistent visual outputs, even with varying performance.

I think, because of that, 18 out of 23 BackstopJS tests still pass, even though I tested on a different machine than the one used to create the reference images. However, 15 tests still fail, which highlights how difficult it is to control the effects of animation performance.

2025-03-21 06:58 UTC, closed without merging